version: "3"

volumes:
  database:

services:
  database:
    image: postgres:16-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typecho
      - POSTGRES_USER=typecho
      - POSTGRES_PASSWORD=TyP3ch0_8L0g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  blog:
    # docker run --name typecho-server -e TYPECHO_SITE_URL=https://your-domain.com -d joyqi/typecho:nightly-php7.4-apache
    image: joyqi/typecho:nightly-php7.4-fpm
    restart: on-failure
    volumes:
      - ./blog/usr/themes:/app/usr/themes:ro
    environment:
      - TYPECHO_SITE_URL=https://simpleblog.ctf.buptmerak.cn
      - TYPECHO_DB_ADAPTER=Pdo_Pgsql
      - TYPECHO_DB_HOST=database
      - TYPECHO_DB_PORT=5432
      - TYPECHO_DB_DATABASE=typecho
      - TYPECHO_DB_USER=typecho
      - TYPECHO_DB_PASSWORD=TyP3ch0_8L0g
      - TYPECHO_INSTALL=1
    depends_on:
      database:
        condition: service_healthy

  server:
    image: caddy:latest
    
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./blog:/app:ro
    ports:
      - "127.0.0.1:80:80"
    depends_on: [blog]
  
  bot:
    build:
      context: ./api
    environment:
      - PORT=4000
      - DOMAIN=simpleblog.ctf.buptmerak.cn
      - TURNSTILE_SITE_KEY=0x4AAAAAAALibk91MmiZbrXh
      - TURNSTILE_SECRET_KEY=0x4AAAAAAALiboEqKDBYPJc-saHCrYeLk50
      - FLAG=RealButterCookiesFromHusky
    init: true
    security_opt:
      - seccomp=chrome.json
    restart: on-failure
    depends_on:
      - server
